language: c
sudo: required
script: bash -ex .travis-vult.sh
env:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - llvm-3.8-dev